baseURL = 'https://www.clubpleinairsainteagathe.com'
languageCode = 'fr-ca'
title = 'Club plein air Sainte-Agathe-des-Monts'
theme = 'ananke'
DefaultContentLanguage = "fr"
[params]
recent_posts_number = 1
