baseURL = 'https://dhdaines.github.io/cpasadm'
languageCode = 'fr-ca'
title = 'Club plein air Sainte-Agathe-des-Monts'
theme = 'ananke'
DefaultContentLanguage = "fr"
[params]
recent_posts_number = 1
body_classes = "helvetica"
short_title = "Plein air Sainte-Agathe"
