backend:
  name: github
  repo: dhdaines/cpasadm
  branch: main
media_folder: static/images
public_folder: /cpasadm/images
collections:
  - name: 'nouvelles'
    label: 'Nouvelles et activités'
    folder: 'content/post'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
